In [1]:
import numpy as np
import pandas as pd

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(-5,4)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3])

In [13]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [19]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [21]:
np.logspace(10,50,10)

array([1.00000000e+10, 2.78255940e+14, 7.74263683e+18, 2.15443469e+23,
       5.99484250e+27, 1.66810054e+32, 4.64158883e+36, 1.29154967e+41,
       3.59381366e+45, 1.00000000e+50])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((4,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [34]:
np.empty((2,3))

array([[4.65990634e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [44]:
np.eye(10)*5

array([[5., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]])

In [67]:
a1 = np.random.randint(11, 22 , (4,5))

In [68]:
a1

array([[14, 20, 13, 20, 16],
       [21, 21, 12, 21, 11],
       [19, 20, 17, 21, 19],
       [17, 18, 21, 17, 11]])